
package com.everis.academia.java.agenda.digital.web.soap;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CidadeSOAP", targetNamespace = "http://soap.web.digital.agenda.java.academia.everis.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CidadeSOAP {


    /**
     * 
     * @param cidade
     * @return
     *     returns java.util.List<com.everis.academia.java.agenda.digital.web.soap.Cidade>
     * @throws BusinessException_Exception
     */
    @WebMethod
    @WebResult(name = "cidade", targetNamespace = "")
    @RequestWrapper(localName = "read", targetNamespace = "http://soap.web.digital.agenda.java.academia.everis.com/", className = "com.everis.academia.java.agenda.digital.web.soap.Read")
    @ResponseWrapper(localName = "readResponse", targetNamespace = "http://soap.web.digital.agenda.java.academia.everis.com/", className = "com.everis.academia.java.agenda.digital.web.soap.ReadResponse")
    @Action(input = "http://soap.web.digital.agenda.java.academia.everis.com/CidadeSOAP/readRequest", output = "http://soap.web.digital.agenda.java.academia.everis.com/CidadeSOAP/readResponse", fault = {
        @FaultAction(className = BusinessException_Exception.class, value = "http://soap.web.digital.agenda.java.academia.everis.com/CidadeSOAP/read/Fault/BusinessException")
    })
    public List<Cidade> read(
        @WebParam(name = "cidade", targetNamespace = "")
        Cidade cidade)
        throws BusinessException_Exception
    ;

    /**
     * 
     * @param cidade
     * @throws BusinessException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "create", targetNamespace = "http://soap.web.digital.agenda.java.academia.everis.com/", className = "com.everis.academia.java.agenda.digital.web.soap.Create")
    @ResponseWrapper(localName = "createResponse", targetNamespace = "http://soap.web.digital.agenda.java.academia.everis.com/", className = "com.everis.academia.java.agenda.digital.web.soap.CreateResponse")
    @Action(input = "http://soap.web.digital.agenda.java.academia.everis.com/CidadeSOAP/createRequest", output = "http://soap.web.digital.agenda.java.academia.everis.com/CidadeSOAP/createResponse", fault = {
        @FaultAction(className = BusinessException_Exception.class, value = "http://soap.web.digital.agenda.java.academia.everis.com/CidadeSOAP/create/Fault/BusinessException")
    })
    public void create(
        @WebParam(name = "cidade", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<Cidade> cidade)
        throws BusinessException_Exception
    ;

}
